markdown: rdiscount
permalink: /:year/:month/:day/:title/
url: http://www.waikeungshen.info
author: waikeungshen
email: waikeungshen@gmail.com
name: WaikeungShen'Blog
github: waikeung
weibo: waikeungshen
pygments: true
safe: true
paginate: 16
auto: true

